"""add_id_graphdata

Revision ID: 16cafa7ff0ce
Revises: e0cd71059377
Create Date: 2021-12-23 02:48:51.191828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16cafa7ff0ce'
down_revision = 'e0cd71059377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graphData', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_index('graphData_time_idx', table_name='graphData')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('graphData_time_idx', 'graphData', ['time'], unique=False)
    op.drop_column('graphData', 'id')
    # ### end Alembic commands ###
