"""Add toggle

Revision ID: 2517bfd62b9d
Revises: a0d1d33506c3
Create Date: 2021-11-25 10:48:55.625002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2517bfd62b9d'
down_revision = 'a0d1d33506c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('toggle', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'toggle')
    # ### end Alembic commands ###
