"""Set groupId as foreign key

Revision ID: 28ba6976c1bc
Revises: 7db537b8750a
Create Date: 2021-11-10 11:52:26.341746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28ba6976c1bc'
down_revision = '7db537b8750a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'devices', 'groups', ['groupId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    # ### end Alembic commands ###
