"""Make group's name unique

Revision ID: a0d1d33506c3
Revises: 28ba6976c1bc
Create Date: 2021-11-10 21:30:56.088304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d1d33506c3'
down_revision = '28ba6976c1bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'groups', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='unique')
    # ### end Alembic commands ###
