"""add_device_unique_fields

Revision ID: a544d1b2f2da
Revises: 2517bfd62b9d
Create Date: 2021-12-20 13:58:00.944394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a544d1b2f2da'
down_revision = '2517bfd62b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'devices', ['name'])
    op.create_unique_constraint(None, 'devices', ['ip'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='unique')
    op.drop_constraint(None, 'devices', type_='unique')
    # ### end Alembic commands ###
