"""add_unique_name_device

Revision ID: a79ded195005
Revises: e0cd71059377
Create Date: 2021-12-21 21:47:18.385579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a79ded195005'
down_revision = 'e0cd71059377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'devices', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='unique')
    # ### end Alembic commands ###
