"""Add graph tables

Revision ID: e0cd71059377
Revises: 7db537b8750a
Create Date: 2021-11-08 08:44:13.898236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0cd71059377'
down_revision = '7db537b8750a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graphs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deviceId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('axisLabel', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['deviceId'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graphData',
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('graphId', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['graphId'], ['graphs.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('graphData')
    op.drop_table('graphs')
    # ### end Alembic commands ###
